steps:
  # Build the container image
  - name: 'asia.gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia.gcr.io/$PROJECT_ID/repeater4gcsr'
      - '.'

images:
  - 'asia.gcr.io/$PROJECT_ID/repeater4gcsr'
